/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.48
 * Generated at: 2017-12-31 08:28:41 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class loginPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1512977094418L));
    _jspx_dependants.put("jar:file:/D:/code/cwweb_git/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cwweb/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/D:/code/cwweb_git/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cwweb/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
pageContext.setAttribute("webpath", path);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("        \r\n");
      out.write("        <title>后台管理系统</title>\r\n");
      out.write("        \r\n");
      out.write("        <meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("        <meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("        <meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("        <meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("        <meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("        <!--\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("        -->      \r\n");
      out.write("        <link href=\"static/css/login.css\" rel=\"stylesheet\" rev=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("        \r\n");
      out.write("        <link href=\"static/css/demo.css\" rel=\"stylesheet\" rev=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("        \r\n");
      out.write("        <script type=\"text/javascript\" src=\"static/js/jquery1.42.min.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        <script type=\"text/javascript\" src=\"static/js/jquery.SuperSlide.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        <script type=\"text/javascript\" src=\"static/js/Validform_v5.3.2_min.js\"></script>\r\n");
      out.write("        <script>\r\n");
      out.write("      //更换验证码\r\n");
      out.write("        function chageCode(){\r\n");
      out.write("            $('#codeImage').attr('src','user/authCode?abc='+Math.random());//链接后添加Math.random，确保每次产生新的验证码，避免缓存问题。\r\n");
      out.write("        }\r\n");
      out.write("            $(function(){\r\n");
      out.write("            \r\n");
      out.write("                $(\".i-text\").focus(function(){\r\n");
      out.write("                    $(this).addClass('h-light');\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                $(\".i-text\").focusout(function(){\r\n");
      out.write("                    $(this).removeClass('h-light');\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                $(\"#username\").focus(function(){\r\n");
      out.write("                    var username = $(this).val();\r\n");
      out.write("                    if(username=='输入账号'){\r\n");
      out.write("                        $(this).val('');\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                $(\"#username\").focusout(function(){\r\n");
      out.write("                    var username = $(this).val();\r\n");
      out.write("                    if(username==''){\r\n");
      out.write("                        $(this).val('输入账号');\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                $(\"#password\").focus(function(){\r\n");
      out.write("                    var username = $(this).val();\r\n");
      out.write("                    if(username=='输入密码'){\r\n");
      out.write("                        $(this).val('');\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                $(\"#yzm\").focus(function(){\r\n");
      out.write("                    var username = $(this).val();\r\n");
      out.write("                    if(username=='输入验证码'){\r\n");
      out.write("                    $(this).val('');\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                $(\"#yzm\").focusout(function(){\r\n");
      out.write("                    var username = $(this).val();\r\n");
      out.write("                    if(username==''){\r\n");
      out.write("                    $(this).val('输入验证码');\r\n");
      out.write("                    }\r\n");
      out.write("                });\r\n");
      out.write("                \r\n");
      out.write("                $(\".registerform\").Validform({\r\n");
      out.write("                    tiptype:function(msg,o,cssctl){\r\n");
      out.write("                        var objtip=$(\".error-box\");\r\n");
      out.write("                        cssctl(objtip,o.type);\r\n");
      out.write("                        objtip.text(msg);\r\n");
      out.write("                    },\r\n");
      out.write("                    ajaxPost:true\r\n");
      out.write("                });\r\n");
      out.write("            });\r\n");
      out.write("            \r\n");
      out.write("            function login() {\r\n");
      out.write("                $.ajax({\r\n");
      out.write("                //几个参数需要注意一下\r\n");
      out.write("                  type: \"GET\",//方法类型\r\n");
      out.write("                  dataType: \"json\",//服务端接收的数据类型\r\n");
      out.write("                  url: \"user/userCheck\",//url\r\n");
      out.write("                  async: true,\r\n");
      out.write("                  data: {username:$(\"#username\").val(), password:$(\"#password\").val(), strCode:$(\"#yzm\").val()},\r\n");
      out.write("                  success: function (result) {\r\n");
      out.write("                    console.log(result);//打印服务端返回的数据(调试用)\r\n");
      out.write("                    if (result.checkCode == 200) {\r\n");
      out.write("                    \talert(\"SUCCESS\");\r\n");
      out.write("                    \tchageCode()\r\n");
      out.write("                    \twindow.location.href = 'user/mainPage';\r\n");
      out.write("                      \r\n");
      out.write("                    } else {\r\n");
      out.write("                    \talert(\"失败\");\r\n");
      out.write("                    };\r\n");
      out.write("                  },\r\n");
      out.write("                  error : function() {\r\n");
      out.write("                    alert(\"异常！\");\r\n");
      out.write("                  }\r\n");
      out.write("                });\r\n");
      out.write("              }\r\n");
      out.write("        </script>\r\n");
      out.write("    </head>\r\n");
      out.write("  \r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"header\">\r\n");
      out.write("            <h1 class=\"headerLogo\"><a title=\"后台管理系统\" target=\"_blank\" ><img alt=\"logo\" src=\"\"></a></h1>\r\n");
      out.write("            <div class=\"headerNav\">\r\n");
      out.write("                <a target=\"_blank\" href=\"#\">菜单一</a>\r\n");
      out.write("                <a target=\"_blank\" href=\"#\">菜单二</a>\r\n");
      out.write("                <a target=\"_blank\" href=\"#\">菜单三</a>\r\n");
      out.write("                <a target=\"_blank\" href=\"#\">菜单四</a>\r\n");
      out.write("                <a target=\"_blank\" href=\"#\">帮助</a>    \r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("        \r\n");
      out.write("        <div class=\"banner\">\r\n");
      out.write("        <div class=\"login-aside\">\r\n");
      out.write("            <div id=\"o-box-up\"></div>\r\n");
      out.write("            <div id=\"o-box-down\"  style=\"table-layout:fixed;\">\r\n");
      out.write("                <div class=\"error-box\"></div>\r\n");
      out.write("                <form  id = \"registerform\" class=\"registerform\" onsubmit=\"return false\" action=\"##\" method=\"post\">\r\n");
      out.write("                    <div class=\"fm-item\">\r\n");
      out.write("                        <label for=\"logonId\" class=\"form-label\">登录帐号：</label>\r\n");
      out.write("                        <input type=\"text\" value=\"输入账号\" maxlength=\"100\" id=\"username\" class=\"i-text\" datatype=\"s6-18\" errormsg=\"用户名至少6个字符,最多18个字符！\"  >    \r\n");
      out.write("                        <div class=\"ui-form-explain\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                \r\n");
      out.write("                    <div class=\"fm-item\">\r\n");
      out.write("                        <label for=\"logonId\" class=\"form-label\">登陆密码：</label>\r\n");
      out.write("                        <input type=\"password\" value=\"\" maxlength=\"100\" id=\"password\" class=\"i-text\" datatype=\"*6-16\" nullmsg=\"请输入密码！\" errormsg=\"密码范围在6~16位之间！\">    \r\n");
      out.write("                        <div class=\"ui-form-explain\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                \r\n");
      out.write("                    <div class=\"fm-item pos-r\">\r\n");
      out.write("                        <label for=\"logonId\" class=\"form-label\">验证码</label>\r\n");
      out.write("                        <input type=\"text\" value=\"输入验证码\" maxlength=\"100\" id=\"yzm\" class=\"i-text yzm\" nullmsg=\"请输入验证码！\" >    \r\n");
      out.write("                        <!--  <div class=\"ui-form-explain\"><img src=\"user/authCode\" onclick=\"chageCode()\" title=\"图片看不清？点击重新得到验证码\" style=\"cursor:pointer\" class=\"yzm-img\" /></div>-->\r\n");
      out.write("                        <label class=\"ui-form-explain\"><img type=\"image\" src=\"user/authCode\" id=\"codeImage\" onclick=\"chageCode()\" title=\"图片看不清？点击重新得到验证码\" style=\"cursor:pointer;\" class=\"yzm-img\"/></label>\r\n");
      out.write("                        <label style=\"margin-left: 80px\"><a onclick=\"chageCode()\" style=\"cursor:pointer;\">换一张</a></label>\r\n");
      out.write("                    </div>\r\n");
      out.write("                  \r\n");
      out.write("                    <div class=\"fm-item\">\r\n");
      out.write("                        <label for=\"logonId\" class=\"form-label\"></label>\r\n");
      out.write("                        <input type=\"button\" onclick=\"login()\" value=\"\" tabindex=\"4\" id=\"send-btn\" class=\"btn-login\"> \r\n");
      out.write("                        <div class=\"ui-form-explain\"></div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("            <div class=\"bd\">\r\n");
      out.write("                <ul>\r\n");
      out.write("                    <li style=\"background:url(static/themes/theme-pic1.jpg) #CCE1F3 center 0 no-repeat;\"></li>\r\n");
      out.write("                    <li style=\"background:url(static/themes/theme-pic2.jpg) #BCE0FF center 0 no-repeat;\"></li>\r\n");
      out.write("                </ul>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"hd\"><ul></ul></div>\r\n");
      out.write("        </div>\r\n");
      out.write("        <script type=\"text/javascript\">jQuery(\".banner\").slide({ titCell:\".hd ul\", mainCell:\".bd ul\", effect:\"fold\",  autoPlay:true, autoPage:true, trigger:\"click\" });</script>\r\n");
      out.write("        <div class=\"banner-shadow\"></div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
