/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.48
 * Generated at: 2017-12-31 08:31:54 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class mainPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1512977094418L));
    _jspx_dependants.put("jar:file:/D:/code/cwweb_git/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cwweb/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/D:/code/cwweb_git/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cwweb/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
pageContext.setAttribute("webpath", path);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("        \r\n");
      out.write("        <title>后台管理系统</title>\r\n");
      out.write("        \r\n");
      out.write("        <meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("        <meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("        <meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("        <meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("        <meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("        <!--\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("        -->      \r\n");
      out.write(" \r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"static/bootstrap/dist/css/bootstrap.min.css\" />\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"static/bootstrap/dist/css/bootstrap-theme.min.css\" />\r\n");
      out.write("        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->\r\n");
      out.write("        <link href=\"static/bootstrap/docs/assets/css/ie10-viewport-bug-workaround.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Custom styles for this template -->\r\n");
      out.write("        <script type=\"text/javascript\" src=\"static/js/jquery1.42.min.js\"></script>\r\n");
      out.write("        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->\r\n");
      out.write("        <!--[if lt IE 9]><script src=\"../../assets/js/ie8-responsive-file-warning.js\"></script><![endif]-->\r\n");
      out.write("        <script src=\"static/bootstrap/docs/assets/js/ie-emulation-modes-warning.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("        <script>\r\n");
      out.write("        $(function(){\r\n");
      out.write("        \t//获取所有li的节点\r\n");
      out.write("            var list = document.getElementsByTagName(\"li\");\r\n");
      out.write("            //给每个li绑定事件\r\n");
      out.write("            for(var i = 0;i < list.length;i++){\r\n");
      out.write("                list[i].onclick = function(){\r\n");
      out.write("                    //将节点的颜色变成红色\r\n");
      out.write("                     $(this).addClass(\"active\");\r\n");
      out.write("                     $(this).siblings().removeClass(\"active\");\r\n");
      out.write("                     var src = $(this).children(\"a:eq(0)\").children(\"span:eq(0)\").text();\r\n");
      out.write("                     $('#iframe_body').attr('src', src);\r\n");
      out.write("                }\r\n");
      out.write("            }\r\n");
      out.write("        });\r\n");
      out.write("        </script>\r\n");
      out.write("        \r\n");
      out.write("        <style type=\"text/css\">\r\n");
      out.write("        /* Hide for mobile, show later */\r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            \r\n");
      out.write("            /* Sidebar navigation */\r\n");
      out.write("            .nav-sidebar {\r\n");
      out.write("              background-color: #D1EEEE;\r\n");
      out.write("              margin-right: -14px; /* 20px padding + 1px border */\r\n");
      out.write("              margin-bottom: 13px;\r\n");
      out.write("              margin-left: -14px;\r\n");
      out.write("            }\r\n");
      out.write("            .nav-sidebar > li > a {\r\n");
      out.write("              padding-right: 20px;\r\n");
      out.write("              padding-left: 20px;\r\n");
      out.write("            }\r\n");
      out.write("            .nav-sidebar > .active > a,\r\n");
      out.write("            .nav-sidebar > .active > a:hover,\r\n");
      out.write("            .nav-sidebar > .active > a:focus {\r\n");
      out.write("              color: #fff;\r\n");
      out.write("              background-color: #428bca;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("            .active{\r\n");
      out.write("                color: #fff;\r\n");
      out.write("                background-color: #428bca;\r\n");
      out.write("            }\r\n");
      out.write("            \r\n");
      out.write("        </style>\r\n");
      out.write("    </head>\r\n");
      out.write("  \r\n");
      out.write("    <body>\r\n");
      out.write("        <div class=\"container-fluid\">  \r\n");
      out.write("            <div class=\"row\">  \r\n");
      out.write("                <div  class=\"col-sm-12 col-md-12 sidebar\">  \r\n");
      out.write("                    <iframe src=\"user/header\" class=\"col-sm-12 col-md-12 sidebar\" scrolling=\"no\" height=\"50px\" frameborder=\"0\"></iframe>\r\n");
      out.write("                </div>  \r\n");
      out.write("                <div class=\"col-sm-11 col-md-11 sidebar\" style=\"margin-left: 15px; margin-top: 2px; height: 100%;\">\r\n");
      out.write("     \r\n");
      out.write("                        <div style=\"background-color: #D1EEEE; height: 100%;\" class=\"col-sm-3 col-md-2 sidebar\">\r\n");
      out.write("                          <ul class=\"nav nav-sidebar\">\r\n");
      out.write("                            <li><a>销售详情<span class=\"sr-only\">user/navPage</span> </a></li>\r\n");
      out.write("                            <li><a>商品入库管理 <span class=\"sr-only\">user/inInventory</span></a></li>\r\n");
      out.write("                            <li><a>商品出库管理<span class=\"sr-only\">user/outInventory</span></a></li>\r\n");
      out.write("                            <li><a>总库存信息<span class=\"sr-only\">user/tatolInventory</span></a></li>\r\n");
      out.write("                            <li><a>库存履历 <span class=\"sr-only\">user/resumeInventory</span></a></li>\r\n");
      out.write("                            <li><a>销售管理 <span class=\"sr-only\">user/saleAdmin</span></a></li>\r\n");
      out.write("                            <li><a>财务统计 <span class=\"sr-only\">user/financeStatistics</span></a></li>\r\n");
      out.write("                            <li><a>员工管理<span class=\"sr-only\">user/staffAdmin</span> </a></li>\r\n");
      out.write("                            <li><a>用户管理<span class=\"sr-only\">user/userAdmin</span></a></li>\r\n");
      out.write("                            <li><a>商品信息管理<span class=\"sr-only\">user/commodityAdmin</span></a></li>\r\n");
      out.write("                            <li><a>订单管理 <span class=\"sr-only\">user/orderAdmin</span></a></li>\r\n");
      out.write("                          </ul>\r\n");
      out.write("                        </div>\r\n");
      out.write("                        <div class=\"col-sm-9 col-md-10 sidebar\">  \r\n");
      out.write("                            <iframe id =\"iframe_body\" src=\"user/navPage\" width=\"100%\"  scrolling=\"no\" height=\"100%\" frameborder=\"0\"></iframe>\r\n");
      out.write("                        </div>  \r\n");
      out.write("               \r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("              \r\n");
      out.write("            <script>  \r\n");
      out.write("              \r\n");
      out.write("            </script>  \r\n");
      out.write("        </div>  \r\n");
      out.write("        <!-- Bootstrap core JavaScript\r\n");
      out.write("    ================================================== -->\r\n");
      out.write("    <!-- Placed at the end of the document so the pages load faster -->\r\n");
      out.write("    <script src=\"https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("    <script src=\"https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->\r\n");
      out.write("    <script src=\"static/bootstrap/docs/assets/js/vendor/holder.min.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"static/js/jquery-1.8.3.js\"></script>\r\n");
      out.write("    <script type=\"text/javascript\" src=\"static/js/jquery1.42.min.js\"></script>\r\n");
      out.write("    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->\r\n");
      out.write("    <script src=\"static/bootstrap/docs/assets/js/ie10-viewport-bug-workaround.js\"></script>\r\n");
      out.write("        \r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
