/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.48
 * Generated at: 2017-12-31 08:56:32 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.WEB_002dINF.views;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.util.*;

public final class navPage_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(3);
    _jspx_dependants.put("/WEB-INF/lib/jstl-1.2.jar", Long.valueOf(1512977094418L));
    _jspx_dependants.put("jar:file:/D:/code/cwweb_git/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cwweb/WEB-INF/lib/jstl-1.2.jar!/META-INF/c.tld", Long.valueOf(1153356282000L));
    _jspx_dependants.put("jar:file:/D:/code/cwweb_git/.metadata/.plugins/org.eclipse.wst.server.core/tmp0/wtpwebapps/cwweb/WEB-INF/lib/jstl-1.2.jar!/META-INF/fmt.tld", Long.valueOf(1153356282000L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");

String path = request.getContextPath();
String basePath = request.getScheme()+"://"+request.getServerName()+":"+request.getServerPort()+path+"/";
pageContext.setAttribute("webpath", path);

      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\">\r\n");
      out.write("<html>\r\n");
      out.write("    <head>\r\n");
      out.write("        <base href=\"");
      out.print(basePath);
      out.write("\">\r\n");
      out.write("        \r\n");
      out.write("        <title>后台管理系统</title>\r\n");
      out.write("        \r\n");
      out.write("        <meta http-equiv=\"pragma\" content=\"no-cache\">\r\n");
      out.write("        <meta http-equiv=\"cache-control\" content=\"no-cache\">\r\n");
      out.write("        <meta http-equiv=\"expires\" content=\"0\">    \r\n");
      out.write("        <meta http-equiv=\"keywords\" content=\"keyword1,keyword2,keyword3\">\r\n");
      out.write("        <meta http-equiv=\"description\" content=\"This is my page\">\r\n");
      out.write("        <!--\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"styles.css\">\r\n");
      out.write("        -->      \r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"static/bootstrap/dist/css/bootstrap.min.css\" />\r\n");
      out.write("        <link rel=\"stylesheet\" type=\"text/css\" href=\"static/bootstrap/dist/css/bootstrap-theme.min.css\" />\r\n");
      out.write("        <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->\r\n");
      out.write("        <link href=\"static/bootstrap/docs/assets/css/ie10-viewport-bug-workaround.css\" rel=\"stylesheet\">\r\n");
      out.write("\r\n");
      out.write("        <!-- Custom styles for this template -->\r\n");
      out.write("        <link href=\"static/css/dashboard.css\" rel=\"stylesheet\" type=\"text/css\" media=\"all\" />\r\n");
      out.write("\r\n");
      out.write("        <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->\r\n");
      out.write("        <!--[if lt IE 9]><script src=\"../../assets/js/ie8-responsive-file-warning.js\"></script><![endif]-->\r\n");
      out.write("        <script src=\"static/bootstrap/docs/assets/js/ie-emulation-modes-warning.js\"></script>\r\n");
      out.write("        <script type=\"text/javascript\" src=\"static/js/echarts.js\"></script>\r\n");
      out.write("       \r\n");
      out.write("    </head>\r\n");
      out.write("  \r\n");
      out.write("    <body>\r\n");
      out.write("    \t\t\r\n");
      out.write("          <div class=\"col-sm-11 col-sm-offset-1 col-md-11 col-md-offset-1 main\">\r\n");
      out.write("          <h1 class=\"page-header\">销售详情</h1>\r\n");
      out.write("\r\n");
      out.write("          <div class=\"row placeholders\">\r\n");
      out.write("            <div class=\"col-xs-6 col-sm-6 placeholder\">\r\n");
      out.write("                <!-- <img src=\"data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==\" width=\"200\" height=\"200\" class=\"img-responsive\" alt=\"Generic placeholder thumbnail\"> -->\r\n");
      out.write("                <!-- 为 ECharts 准备一个具备大小（宽高）的 DOM -->\r\n");
      out.write("                <div id=\"main\" class=\"col-xs-12 col-sm-12 placeholder\" style=\"height: 30%\"></div>\r\n");
      out.write("\t\t        <script>\r\n");
      out.write("\t\t            // 基于准备好的dom，初始化echarts实例\r\n");
      out.write("\t\t            var myChart = echarts.init(document.getElementById('main'));\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t            // 指定图表的配置项和数据\r\n");
      out.write("\t\t            var option = {\r\n");
      out.write("\t\t                title: {\r\n");
      out.write("\t\t                    text: '销售记录'\r\n");
      out.write("\t\t                },\r\n");
      out.write("\t\t                tooltip: {},\r\n");
      out.write("\t\t                legend: {\r\n");
      out.write("\t\t                    data:['销量']\r\n");
      out.write("\t\t                },\r\n");
      out.write("\t\t                xAxis: {\r\n");
      out.write("\t\t                    data: [\"衬衫\",\"羊毛衫\",\"雪纺衫\",\"裤子\",\"高跟鞋\",\"袜子\"]\r\n");
      out.write("\t\t                },\r\n");
      out.write("\t\t                yAxis: {\r\n");
      out.write("\t\t                \t\r\n");
      out.write("\t\t                },\r\n");
      out.write("\t\t                series: [{\r\n");
      out.write("\t\t                    name: '销量',\r\n");
      out.write("\t\t                    type: 'bar',\r\n");
      out.write("\t\t                    data: [5, 20, 36, 10, 10, 20]\r\n");
      out.write("\t\t                }]\r\n");
      out.write("\t\t            };\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t            // 使用刚指定的配置项和数据显示图表。\r\n");
      out.write("\t\t            myChart.setOption(option);\r\n");
      out.write("                </script>\r\n");
      out.write("                <h4>柱状图</h4>\r\n");
      out.write("              <span class=\"text-muted\">月度销量</span>\r\n");
      out.write("            </div>\r\n");
      out.write("            <div class=\"col-xs-6 col-sm-6 placeholder\">\r\n");
      out.write("<!--               <img src=\"data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==\" width=\"200\" height=\"200\" class=\"img-responsive\" alt=\"Generic placeholder thumbnail\">\r\n");
      out.write(" -->              \r\n");
      out.write(" \t\t\t\t<div id=\"main_01\" class=\"col-xs-12 col-sm-12 placeholder\" style=\"height: 30%\"></div>\r\n");
      out.write("\t\t        <script>\r\n");
      out.write("\t\t            // 基于准备好的dom，初始化echarts实例\r\n");
      out.write("\t\t            var myChart = echarts.init(document.getElementById('main_01'));\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t            // 指定图表的配置项和数据\r\n");
      out.write("\t\t            var option = {\r\n");
      out.write("\t\t                title: {\r\n");
      out.write("\t\t                    text: '销售记录'\r\n");
      out.write("\t\t                },\r\n");
      out.write("\t\t                tooltip: {},\r\n");
      out.write("\t\t                legend: {\r\n");
      out.write("\t\t                    data:['销量']\r\n");
      out.write("\t\t                },\r\n");
      out.write("\t\t                xAxis: {\r\n");
      out.write("\t\t                    data: [\"衬衫\",\"羊毛衫\",\"雪纺衫\",\"裤子\",\"高跟鞋\",\"袜子\"]\r\n");
      out.write("\t\t                },\r\n");
      out.write("\t\t                yAxis: {\r\n");
      out.write("\t\t                \t\r\n");
      out.write("\t\t                },\r\n");
      out.write("\t\t                series: [{\r\n");
      out.write("\t\t                    name: '销量',\r\n");
      out.write("\t\t                    type: 'bar',\r\n");
      out.write("\t\t                    data: [5, 20, 36, 10, 10, 20]\r\n");
      out.write("\t\t                }]\r\n");
      out.write("\t\t            };\r\n");
      out.write("\t\t    \r\n");
      out.write("\t\t            // 使用刚指定的配置项和数据显示图表。\r\n");
      out.write("\t\t            myChart.setOption(option);\r\n");
      out.write("                </script>\r\n");
      out.write(" \t\t\t <h4>饼状图</h4>\r\n");
      out.write("              <span class=\"text-muted\">出入库对比图</span>\r\n");
      out.write("            </div>\r\n");
      out.write("          \r\n");
      out.write("          </div>\r\n");
      out.write("\r\n");
      out.write("          <h2 class=\"sub-header\">库存详情</h2>\r\n");
      out.write("          <div class=\"table-responsive\">\r\n");
      out.write("            <table class=\"table table-striped\">\r\n");
      out.write("              <thead>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <th>序号</th>\r\n");
      out.write("                  <th>商品编号</th>\r\n");
      out.write("                  <th>商品名称</th>\r\n");
      out.write("                  <th>商品价格</th>\r\n");
      out.write("                  <th>商品库存数量</th>\r\n");
      out.write("                  <th>计量单位</th>\r\n");
      out.write("                </tr>\r\n");
      out.write("              </thead>\r\n");
      out.write("              <tbody>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td>001</td>\r\n");
      out.write("                  <td>000001</td>\r\n");
      out.write("                  <td>毛线大衣</td>\r\n");
      out.write("                  <td>2394.55</td>\r\n");
      out.write("                  <td>120</td>\r\n");
      out.write("                  <td>件</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("                <tr>\r\n");
      out.write("                  <td>002</td>\r\n");
      out.write("                  <td>000002</td>\r\n");
      out.write("                  <td>皮革大衣</td>\r\n");
      out.write("                  <td>99999</td>\r\n");
      out.write("                  <td>13</td>\r\n");
      out.write("                  <td>件</td>\r\n");
      out.write("                </tr>\r\n");
      out.write("\r\n");
      out.write("              </tbody>\r\n");
      out.write("            </table>\r\n");
      out.write("          </div>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("    \r\n");
      out.write("    <!-- Bootstrap core JavaScript\r\n");
      out.write("    ================================================== -->\r\n");
      out.write("    <!-- Placed at the end of the document so the pages load faster -->\r\n");
      out.write("    <script src=\"https://cdn.bootcss.com/jquery/1.12.4/jquery.min.js\"></script>\r\n");
      out.write("    <script>window.jQuery || document.write('<script src=\"static/bootstrap/docs/assets/js/vendor/jquery.min.js\"><\\/script>')</script>\r\n");
      out.write("    <script src=\"https://cdn.bootcss.com/bootstrap/3.3.7/js/bootstrap.min.js\"></script>\r\n");
      out.write("    <!-- Just to make our placeholder images work. Don't actually copy the next line! -->\r\n");
      out.write("    <script src=\"static/bootstrap/docs/assets/js/vendor/holder.min.js\"></script>\r\n");
      out.write("    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->\r\n");
      out.write("    <script src=\"static/bootstrap/docs/assets/js/ie10-viewport-bug-workaround.js\"></script>\r\n");
      out.write("    \r\n");
      out.write("    </body>\r\n");
      out.write("</html>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
